config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  resources :partners do
    resources :appointments, only: %i[new create]
  end
  resources :appointments, only: %i[index destroy]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :user
  belongs_to :partner
  validates :start_time, presence: true
  validates :end_time, presence: true
end

app/models/partner.rb
class Partner < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  belongs_to :user
  has_many :appointments, dependent: :destroy
  has_many :users, through: :appointments
  has_one_attached :photo_url

  # has_one_attached :photo
  GENDER = ["Female", "Male", "Other"]
  validates :gender, presence: true, inclusion: { in: GENDER }
  TEMPERAMENT = ["Extrovert", "Neutral", "Shy"]
  validates :temperament, presence: true, inclusion: { in: TEMPERAMENT }
  INTEREST = ["Nature", "Sport", "Reading", "Music", "Gaming", "Traveling"]
  validates :interest, presence: true, inclusion: { in: INTEREST }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :appointments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_user, only: %i[new create]
  before_action :set_partner, only: %i[new create]

  def index
    @appointments = Appointment.all
  end

  def new
    @appointment = Appointment.new
  end

  def create
    @appointment = Appointment.new(params_appointment)
    @appointment.partner = @partner
    @appointment.user = @user

    if @appointment.save
      redirect_to appointments_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @appointment = Appointment.find(params[:id])

    @appointment.destroy
    redirect_to appointments_path, status: :see_other
  end

  private

  def params_appointment
    params.require(:appointment).permit(:start_time, :end_time, :user_id, :partner_id)
  end

  def set_user
    @user = current_user
  end

  def set_partner
    @partner = Partner.find(params[:partner_id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
  end
end

app/controllers/partners_controller.rb
class PartnersController < ApplicationController
  before_action :set_partner, only: [:show, :edit, :update, :destroy]
  def index
    @partners = Partner.all

    if params[:interest].present?
      @partners = Partner.where(interest: params[:interest])
    end
    if params[:temperament].present?
      @partners = Partner.where(temperament: params[:temperament])
    end

    # The `geocoded` scope filters only partners with coordinates
    @markers = @partners.geocoded.map do |partner|
      {
        lat: partner.latitude,
        lng: partner.longitude,
        image_url: helpers.cloudinary_url(partner.photo_url.key),
        info_window: render_to_string(partial: "info_window", locals: {partner: partner})
      }
    end
  end

  def show
  end

  def new
    @partner = Partner.new
  end

  def create
    @partner = Partner.new(partner_params)
    @partner.user = current_user
    if @partner.save
      redirect_to partner_path(@partner)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @partner.update(partner_params)
      redirect_to @partner, notice: 'Your Profile Was Successfully Updated!'
    else
      render :edit
    end
  end

  def destroy
    @partner.destroy
    redirect_to partners_path, status: :see_other
  end

  private

  def set_partner
    @partner = Partner.find(params[:id])
  end

  def partner_params
    params.require(:partner).permit(:first_name, :last_name, :gender, :address, :temperament, :interest, :age, :photo_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/appointments/index.html.erb
<div id="cardix-app" >
  <h1>My Appointments</h1>
  <% if  @appointments.all == []  %>
    <h3>You don't have appointments yet !</h3>
  <% else %>
    <ul class="list-unstyled">
      <% @appointments.each do |appointment| %>
          <li class="mb-2">
            <div class="card-product" style="justify-content: space-between;">
              <div style="display: flex; align-items: center;">
                <%= link_to partner_path(appointment.partner) do %>
                  <% if appointment.partner.photo_url.attached? %>
                    <%= cl_image_tag appointment.partner.photo_url.key, height: 120, width: 120, crop: :fill %>
                  <% end %>
                <% end %>
                <div class="card-product-infos">
                  <%= link_to partner_path(appointment.partner) do %>
                    <h2>From <%= appointment.start_time.strftime("%b %d, %Y")  %> to <%= appointment.end_time.strftime("%b %d, %Y") %> </h2>
                    <p>I will spend good time with <strong><%= appointment.partner.first_name %></strong>!</p>
                  <% end %>
                </div>
              </div>
              <%= link_to '<i class="fa-solid fa-trash" style="font-size: x-large;margin-right: 69px;""></i>'.html_safe, appointment_path(appointment), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class:"text-decoration-none"  %>
            </div>
          </li>
      <% end %>
    </ul>
  <% end %>

      <div id="button-app">
      <%= link_to partners_path do %>
        <button id="msg-app">Map</button>
      <% end %>
    </div>
</div>




<%= render 'shared/footer'%>

app/views/appointments/new.html.erb
<div class="container">
<h1 class="my-5 text-center" style="color: #E6EBEE;">Rent a furendo</h1>

<div style="display: flex; justify-content: center; color: #E6EBEE; font-family: montserrat; ">
<%= simple_form_for [@partner, @appointment], data: { controller: 'flatpickr' } do |f|%>
<%= f.input :start_time, as: :string, input_html: { data: { flatpickr_target: "startTime" } } %>
<%= f.input :end_time, as: :string, input_html: { data: { flatpickr_target: "endTime" } } %>
<%= f.submit "Rent #{@partner.first_name}!", class:'create-partner-button btn-rent link-index-button btn-appointment' %>
<% end %>
</div>

<%= link_to "Back to main", partners_path, class:'link-index-button btn-back btn-appointment', style: "color: #344F73; font-family: montserrat;" %>
</div>

<%= render 'shared/footer'%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RENTARUFurendo</title>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/typed.js/2.0.8/typed.min.js"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.js"></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%# <%= javascript_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
      <%= yield %>
        <p class="notice"><%= notice %></p>
          <p class="alert"><%= alert %></p>

  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://media.npr.org/assets/img/2016/09/01/narcos_203_00873r1_wide-775f1c1b8a3fe57cb17da8361e5e1c165e90d12f.jpg);">
  <div class="container">
    <h1>Do you feel <span id="typed"></span></h1>
    <p>You shouldn't, nobody should</p>
    <%= link_to 'Find ur Furendo 😍', partners_path, class: "btn btn-outline-info btn-lg" %>
  </div>
</div><br>
<%= render 'shared/footer_home'%>

app/views/partners/_info_window.html.erb
<div class="card-product-infos-index">
  <h2><%= link_to "🙋#{partner.first_name}", partner_path(partner) %></h2>
</div>

app/views/partners/edit.html.erb
<div class="container">
<h1>Edit Furendo</h1>
<%= render 'shared/form', partner: @partner %>
<br>
<%= link_to "back", partners_path, class:"btn btn-primary my-2" %>

<div style = "height:100px;"></div>
</div>
<%= render 'shared/footer'%>

app/views/partners/index.html.erb
<%= form_tag partners_path, method: :get, class:"flex-container-search" do %>
  <%= select_tag :interest, options_for_select(Partner::INTEREST), prompt: "Interest", class: "interest" %>
  <%= select_tag :temperament, options_for_select(Partner::TEMPERAMENT), prompt: "Temperament", class: "interest" %>
  <button  style="background-color: #344F73;" >Search</button>
  <%= link_to partners_path do %>
    <button id="msg">Clear</button>
  <% end %>
<% end %>



<div class="flex-index" style="height: calc(100vh - 229px);"
  data-controller="map"
  data-map-markers-value="<%= @markers.to_json %>"
  data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>" >
</div>

<br>
<%= render 'shared/footer_home'%>

app/views/partners/new.html.erb
<div class="container">
  <%= render 'shared/form', partner: @partner %>
  <button type="button" class="link-index-button btn-back btn-appointment" style="color: #344F73; font-family: montserrat;">
  <%= link_to 'Map', partners_path %>
  </button>
</div>
<%= render 'shared/footer'%>

app/views/partners/show.html.erb
<% price = (20..999).to_a.sample %>


<div id="cardix">
	<h1><%= @partner.first_name %> <%= @partner.last_name %></h1>
    <div class="image-crop">
      <% if @partner.photo_url.attached? %>
        <%= cl_image_tag @partner.photo_url.key, height: 150, width: 150, crop: :fill %>
      <% end %>
    </div>
    <div id="bio">
      <p>Hello, my name is <%= @partner.first_name %> and I'm from <%= @partner.address.split(",")[2] %>! My temperament is <%= @partner.temperament.downcase %> hope you'll get it, also i'm interested in <%= @partner.interest.downcase %>. In case you didnt notice my gender is <%= @partner.gender.downcase %></p>
    </div>
    <div id="stats">
      <div class="col" id="l">
        <p class="stat">$<%= price %>/day </p>
        <p class="label">Price</p>
      </div>
      <div class="col">
        <p class="stat"><%= @partner.temperament %></p>
        <p class="label">Temperament</p>
      </div>
      <div class="col" id="r">
        <p class="stat"><%= @partner.age %> y/o</p>
        <p class="label">Age</p>
      </div>
    </div>
    <div id="buttons">
      <%= link_to new_partner_appointment_path(@partner) do %>
        <button>Rent me!</button>
      <% end %>
      <%= link_to partners_path do %>
        <button id="msg">Back</button>
      <% end %>
    </div>
</div>

<%= render 'shared/footer'%>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="https://tse3.mm.bing.net/th?id=OIP.zBNaBTZ2acOQ3nRyGqC_JwHaJW&pid=Api" target=_blank><i class="fab fa-github"></i></a>
    <a href="https://tse4.mm.bing.net/th?id=OIP.dLO2rZdlFe8qX9VmiWzs_QHaJ4&pid=Api" target=_blank><i class="fab fa-instagram"></i></a>
    <a href="https://tse1.mm.bing.net/th?id=OIP.-DwH0PO5tbZ1l4hA-4U6lAHaFj&pid=Api" target=_blank><i class="fab fa-facebook"></i></a>
    <a href="https://tse2.mm.bing.net/th?id=OIP.-iXHRj9mNpPiVcIJPFZ8_QHaIX&pid=Api" target=_blank><i class="fab fa-twitter"></i></a>
    <a href="https://tse1.explicit.bing.net/th?id=OIP.Pp8ZH3HlV2iyVy2RDVZXWAHaHa&pid=Api" target=_blank><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
  <p>Made with ❤️ in Nice</p>
  </div>
</div>

app/views/shared/_footer_home.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="https://tse3.mm.bing.net/th?id=OIP.zBNaBTZ2acOQ3nRyGqC_JwHaJW&pid=Api" target=_blank><i class="fab fa-github"></i></a>
    <a href="https://tse4.mm.bing.net/th?id=OIP.dLO2rZdlFe8qX9VmiWzs_QHaJ4&pid=Api" target=_blank><i class="fab fa-instagram"></i></a>
    <a href="https://tse1.mm.bing.net/th?id=OIP.-DwH0PO5tbZ1l4hA-4U6lAHaFj&pid=Api" target=_blank><i class="fab fa-facebook"></i></a>
    <a href="https://tse2.mm.bing.net/th?id=OIP.-iXHRj9mNpPiVcIJPFZ8_QHaIX&pid=Api" target=_blank><i class="fab fa-twitter"></i></a>
    <a href="https://tse1.explicit.bing.net/th?id=OIP.Pp8ZH3HlV2iyVy2RDVZXWAHaHa&pid=Api" target=_blank><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
  <p>Made with ❤️ in Nice</p>
  </div>
</div>

app/views/shared/_form.html.erb
<div class="container" style="display: flex; justify-content: center; color: #E6EBEE; font-family: montserrat; ">
<%= simple_form_for partner do |f| %>
  <%= f.input :first_name %>
  <%= f.input :last_name %>
  <%= f.input :gender, collection: Partner::GENDER %>
  <%= f.input :address %>
  <%= f.input :temperament, collection: Partner::TEMPERAMENT %>
  <%= f.input :interest, collection: Partner::INTEREST %>
  <%= f.input :age %>
   <%= f.input :photo_url, as: :file %>
  <%= f.submit "Create/Edit", class:'create-partner-button btn-rent link-index-button btn-appointment' %>
<% end %>
</div>